MySQL replication status check lambda function 에서의 Replication broken 처리 및 README 추가
ridibooks/devops-toolbox pull request #5
Opened 2019-07-29 06:59 UTC by JKtheUnique

- 관련 아사나 태스크: 
- https://app.asana.com/0/339493321132890/1131980994327607
- https://app.asana.com/0/429083196885278/1113253094073754

- https://github.com/ridi/devops-toolbox/pull/4 를 통해 머지 된 replication status check 에서 second behind master 가 null 로 들어오는 경우 (replication broken) 을 처리 하였고 readme 를 추가 하였습니다.

2019-07-29 10:51 UTC, ssaifriend approved these changes

2019-07-29 11:47 UTC, namenu requested changes

2019-07-29 11:47 UTC, namenu commented on mysql/replcation_lambda/README.md
> +[기존 PR](https://github.com/ridi/devops-toolbox/pull/4) 의 설명을 인용했습니다.
이 내용은 README에 없어도 되겠습니다.

2019-07-29 11:47 UTC, namenu commented on mysql/replcation_lambda/README.md
> +- Lambda 런타임은 Node.js 10.x 보다 Node.js 8.10 으로 사용하는 것이 작은 속도 향상이 있습니다. [관련정보](https://epsagon.com/blog/aws-lambda-node-js-10-support-and-benchmark/)
이 부분은 추후에 사실이 아니게 될 수 있습니다. 반면 크게 중요한 부분이 아니므로 제거하는 것이 어떨까 합니다.

2019-07-29 11:47 UTC, namenu commented on mysql/replcation_lambda/README.md
> +- 이벤트 소스는 일정 - 고정비율로 선택후 원하는 주기 (ex. 1분) 를 선택 후 대상 추가를 눌러 위에서 생성한 람다 함수를 선택합니다.
선택 후

2019-07-29 11:47 UTC, namenu commented on mysql/replcation_lambda/index.js
> +        if (secondBehindMaster === null) secondBehindMaster = 999999; // 경보 범위를 넘어서는 임의의 큰 값
스타일 가이드에 따르면 한 줄로 표현이 가능하더라도 반드시 curly brace가 필요합니다.
https://eslint.org/docs/rules/curly

2019-07-29 12:43 UTC, JKtheUnique commented on mysql/replcation_lambda/README.md
> +[기존 PR](https://github.com/ridi/devops-toolbox/pull/4) 의 설명을 인용했습니다.
네 삭제 했습니다.

2019-07-29 12:43 UTC, JKtheUnique commented on mysql/replcation_lambda/README.md
> +- 이벤트 소스는 일정 - 고정비율로 선택후 원하는 주기 (ex. 1분) 를 선택 후 대상 추가를 눌러 위에서 생성한 람다 함수를 선택합니다.
수정 했습니다.

2019-07-29 12:44 UTC, JKtheUnique commented on mysql/replcation_lambda/README.md
> +- Lambda 런타임은 Node.js 10.x 보다 Node.js 8.10 으로 사용하는 것이 작은 속도 향상이 있습니다. [관련정보](https://epsagon.com/blog/aws-lambda-node-js-10-support-and-benchmark/)
네 이정도의 간단한 코드에서는 속도 향상이 크게 체감 될 정도는 아니니 제거토록 하겠습니다.

2019-07-29 12:45 UTC, JKtheUnique commented on mysql/replcation_lambda/index.js
> +        if (secondBehindMaster === null) secondBehindMaster = 999999; // 경보 범위를 넘어서는 임의의 큰 값
스타일 가이드에 따라 다른 부분에 있던 한줄로 표기된 조건문도 수정 하였습니다.

2019-07-30 02:21 UTC, namenu approved these changes

2019-07-30 03:23 UTC, iamchanu commented on mysql/replcation_lambda/README.md
> +## 리플리케이션 모니터링
여기 큰 제목에 `#` 헤더를, 밑에 소제목들에 `##` 헤더를 쓰는 것이 맞을 것 같습니다.

2019-07-30 03:36 UTC, JKtheUnique commented on mysql/replcation_lambda/README.md
> +## 리플리케이션 모니터링
그게 맞는 것 같습니다.

2019-07-30 03:39 UTC, iamchanu approved these changes

2019-08-05 03:48 UTC, mskims commented on mysql/replcation_lambda/index.js
> +                console.log(err);
`reject` 를 호출하는게 낫지 않을까요?

2019-08-06 03:26 UTC, JKtheUnique commented on mysql/replcation_lambda/index.js
> +                console.log(err);
reject 가 호출 되면 handler 에서 잡히겠지요?? 그게 나을 것 같습니다.

2019-08-08 07:19 UTC, Goliathtom approved these changes

2019-08-08 07:20 UTC, Goliathtom approved these changes

2019-08-08 07:25 UTC, mskims approved these changes

2019-08-08 08:15 UTC, merged